Settings:
  #If you would like to give the players the hook on join, set this to true.
  #If they already have the item nothing will happen
  give_on_join: false

  #Set the velocity aka the amount of leap players get when using the grappling hook.
  velocity: 1.0
  #Set the cooldown in seconds between each use.
  cooldown: 2

  #set Enabled to true or false to toggle sounds
  sound:
    enabled: true
    #sound names https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    name: BLOCK_NOTE_BLOCK_PLING

  #Hook messages
  messages:
    actionbar:
      enabled: true
      #Action bar do not support hex colors, so please limit the colors here to bukkit colors.
      message: '&d&l&oWhoosh!'
    title:
      enabled: true
      message: "&#EBC7FFWhoosh!"
    cooldown:
      enabled: true
      title: "&#EBC7FFCan't use this yet!"
      #Do not remove or change the '%this%'.
      subtitle: "&#EBC7FFCooldown: &#BE8CFF%this%&#EBC7FF seconds."


  #Default uses on /gh give <player>
  uses:
    #Adds some basic use stats to the item lore. (Bound to the item)
    enabled: true
    #The default amount given if not specified.
    amount: 60

    #Select the minimum and maximum random number.
    #if you do '/gh give <player> random' instead of a number you will give them a random number between the min and max value.
    random:
      min: 3
      max: 67

    sound:
      enabled: true
      name: ENTITY_GOAT_HORN_BREAK
    message:
      enabled: true

  #Allow players to craft the grappling hook. It's the same as a fishing rod but the string is
  #Needs server restart to take effect.
  crafting:
    enabled: true


